#保险配置
insurance:

   zcgName: 施亚彬 #   运输险固定投保人/被保人姓名
   zcgCardNo: 342501199109126032 #   运输险固定投保人/被保人身份证号
   zcgPhone: 18715637638 #   运输险固定投保人/被保人电话
   zcgMail: 1092347670@qq.com #   运输险固定投保人/被保人邮箱
   zcgAddress: 上海市嘉定区嘉戬公路500号 #   运输险固定投保人/被保人地址
   zcgSustainTime: 12 # 运输险自动往后顺延12小时
#   invoiceUrl: http://www.epicc.com.com.cn/ecooperation/InvoiceConfigController/StartInvoiceConfig.do #   正式环境 请求发票地址
#   insuranceUrl: http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl #   正式环境 投保地址
   invoiceTitle: 上海宠道信息科技 #   发票抬头
   plateFormCode: CPI000865 #   投保平台代码
#   secretKey: Picc89MK8yjq6h7j #   正式环境 秘钥
   insuranceServiceNo: 001001 #   wsdl接口代码
   zfoRiskCode: ZFO #   家责险标识
   zcgRiskCode: ZCG #   运输险标识
   i9qRiskCode: I9Q #   医疗险标识
   policyFolderPrefix: ../../policy/ #   电子保单保存地址
   policyRealpath: /home/policy/ #   电子保单预览地址
   invoiceFolderPrefix: ../../invoice/ #   电子发票保存地址
   invoiceRealpath: /home/invoice/ #   电子发票预览地址

#   测试环境相关参数
   secretKey: Picc37mu63ht38mw #   测试环境, 秘钥
   invoiceUrl: http://partnertest.mypicc.com.cn/ecooperation/InvoiceConfigController/StartInvoiceConfig.do #   测试环境 请求发票地址
   insuranceUrl: http://partnertest.mypicc.com.cn/ecooperation/webservice/insure?wsdl #   测试环境 投保地址


