server:
  port: 8086
  servlet:
    context-path: /app_client


#数据库链接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.160.88:3306/chongdao_app_beta
    username: pet
    password: ABcd12#$
  #为null的字段不需要穿给前端
  jackson:
    default-property-inclusion: non_null
#  profiles:
#    active: sms

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.chongdao.client.entitys
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #tomcat配置
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
    maxPostSize: 102400
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true   #是否输出sql
    properties:
      hibernate:
        format_sql: true

#创蓝短信服务
sms:
  url: http://smssh1.253.com/msg/variable/json
  account: N2434702
  password: Ryh6TxCW0Ycbc3
  enable: 1
  SmsIdentifyCode: 【养宠有道】您的登陆验证码为:{$var}

#微信配置
wxconfig:
  xcxAppid: wx601e284d89b5ad6b
  mchId: 1513194061
  notifyUrl: https://www.chongdaopet.com/weixin/pay
  payUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  apiUrl: https://api.weixin.qq.com/sns/jscode2session?grant_type=authorization_code
  secret: 95bc30c8e25484485b53b998bace1d1c
  apiKey : 95bc30c8e25484485b53b998bace1d1c
  gzhAppId: wxd69bd4ce033aca70
  gzhSecret: 437dd549567811195afa051d3f49327a




logging:
  pattern:
    console: "%d - %msg%n"
#  path: /var/log/
#  file: /var/log/tomcat/app_client.log



fdfs:
  so-timeout: 1501 #上传的超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 118.25.190.86:22122
  host: 118.25.190.86

