
package com.chongdao.client.service.insurance.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EcooperationWebService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EcooperationWebService {


    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shortModifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ShortModifyService")
    @ResponseWrapper(localName = "shortModifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ShortModifyServiceResponse")
    public String shortModifyService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insureServiceLianGongBao", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.InsureServiceLianGongBao")
    @ResponseWrapper(localName = "insureServiceLianGongBaoResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.InsureServiceLianGongBaoResponse")
    public String insureServiceLianGongBao(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printProofService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.PrintProofService")
    @ResponseWrapper(localName = "printProofServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.PrintProofServiceResponse")
    public String printProofService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ModifyService")
    @ResponseWrapper(localName = "modifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ModifyServiceResponse")
    public String modifyService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.InsureService")
    @ResponseWrapper(localName = "insureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.InsureServiceResponse")
    public String insureService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newInsureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.NewInsureService")
    @ResponseWrapper(localName = "newInsureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.NewInsureServiceResponse")
    public String newInsureService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shortInsureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ShortInsureService")
    @ResponseWrapper(localName = "shortInsureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.ShortInsureServiceResponse")
    public String shortInsureService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

    /**
     * 
     * @param interfaceNo
     * @param datas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transitService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.TransitService")
    @ResponseWrapper(localName = "transitServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "com.chongdao.client.service.insurance.webservice.TransitServiceResponse")
    public String transitService(
        @WebParam(name = "interfaceNo", targetNamespace = "")
        String interfaceNo,
        @WebParam(name = "datas", targetNamespace = "")
        String datas);

}
