
package com.chongdao.client.service.insurance.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "EcooperationWebServiceService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", wsdlLocation = "http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl")
public class EcooperationWebServiceService
        extends Service
{

    private final static URL ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ECOOPERATIONWEBSERVICESERVICE_EXCEPTION;
    private final static QName ECOOPERATIONWEBSERVICESERVICE_QNAME = new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.epicc.com.cn/ecooperation/webservice/insure?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION = url;
        ECOOPERATIONWEBSERVICESERVICE_EXCEPTION = e;
    }

    public EcooperationWebServiceService() {
        super(__getWsdlLocation(), ECOOPERATIONWEBSERVICESERVICE_QNAME);
    }

    public EcooperationWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECOOPERATIONWEBSERVICESERVICE_QNAME, features);
    }

    public EcooperationWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ECOOPERATIONWEBSERVICESERVICE_QNAME);
    }

    public EcooperationWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECOOPERATIONWEBSERVICESERVICE_QNAME, features);
    }

    public EcooperationWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EcooperationWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EcooperationWebService
     */
    @WebEndpoint(name = "EcooperationWebServicePort")
    public EcooperationWebService getEcooperationWebServicePort() {
        return super.getPort(new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServicePort"), EcooperationWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EcooperationWebService
     */
    @WebEndpoint(name = "EcooperationWebServicePort")
    public EcooperationWebService getEcooperationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServicePort"), EcooperationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECOOPERATIONWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ECOOPERATIONWEBSERVICESERVICE_EXCEPTION;
        }
        return ECOOPERATIONWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
